version: '3.3'  # version of compose format

services:
  rooms-backend:
    build: ./rooms-backend  # path is relative to docker-compose.yml location
    hostname: localhost
    ports:
      - 8082:8082  # host:container
    networks:
      sample:
        aliases:
          - rooms-backend

  rooms-frontend:
    build: ./rooms-frontend
    hostname: localhost
    ports:
      - 80:80  # host:container
    depends_on:
      - rooms-backend                             
    networks:
      sample:
        aliases:
          - rooms-frontend

networks:
  sample: